# Generated by Django 4.0.5 on 2022-06-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=2000)),
                ('update', models.DateField(auto_now=True)),
                ('questions', models.ManyToManyField(related_name='challenges', to='question.question')),
            ],
        ),
    ]
