# Generated by Django 4.0.5 on 2022-06-12 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='candidate.candidate'),
        ),
    ]
