# Generated by Django 4.0.5 on 2022-06-12 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
        ('interview', '0002_interview_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to='challenge.challenge'),
        ),
    ]
