# Generated by Django 4.0.5 on 2022-06-12 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
        ('challenge', '0001_initial'),
        ('question', '0001_initial'),
        ('interview', '0003_interview_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=2000)),
                ('update', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='candidate.candidate')),
                ('challenge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='challenge.challenge')),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interviews', to='interview.interview')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='question.question')),
                ('question_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_options', to='question.questionoption')),
            ],
        ),
    ]
