# Generated by Django 4.0.5 on 2022-06-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_interviewreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewreport',
            name='comments',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
