# Generated by Django 4.0.5 on 2022-06-17 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_alter_interview_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewstatus',
            options={'verbose_name_plural': 'Interview statuses'},
        ),
    ]
